nameOverride: ""

replicaCount: 1

kind: Deployment

image:
  repository: nginx
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

secrets:
  enabled: false
  vault:
    enabled: false
    path: ""

secretConfig: {}

service:
  - name: api
    type: ClusterIP
    targetPort: 8080
    port: 80

ingress:
  enabled: false

liveness:
  enabled: true
  method: http
  service: api
  path: "/actuator/health/liveness"
  initialDelaySeconds: 0
  periodSeconds: 24
  successThreshold: 1
  failureThreshold: 5

readiness:
  enabled: true
  method: http
  service: api
  path: "/actuator/health/readiness"
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  failureThreshold: 3

startup:
  enabled: true
  method: http
  service: api
  path: "/actuator/health/readiness"
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 60

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

volumes: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1

podSpec:
  labels: {}
container: {}
