nameOverride: "frontend"

replicaCount: 2

kind: StatefulSet

image:
  repository: nginx
  pullPolicy: Always
  tag: ""

imagePullSecrets:
  - fintech-harbor

config:
  EXAMPLE: "EXAMPLE"

secretConfig:
  DB_PASSWORD:
    secretName: db-creds
    key: password
  AWS_ACCESS_KEY_ID:
    secretName: aws-creds
    key: access-key-id

secrets:
  enabled: false
  vault:
    enabled: false
    path: ""

fileSecrets:
  - name: file-secret
    path: /etc/file-secret
    source:
      vault:
        enabled: false
        path: ""

service:
  - name: api
    type: ClusterIP
    targetPort: 8080
    port: 80
    annotations: { }
  - name: tcp
    type: NodePort
    targetPort: 9999
    port: 80
    annotations: { }
    nodePort: 30999

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: chart-web.local
      paths:
        - path: /
          pathType: Prefix
          service: web
    - host: chart-debug.local
      paths:
        - path: /
          pathType: Prefix
          service: debug
  tls:
    - secretName: chart-example-tls
      hosts:
        - chart-example.local

liveness:
  enabled: true
  method: http
  service: web
  path: "/"
  initialDelaySeconds: 70
  periodSeconds: 1
  successThreshold: 1
  failureThreshold: 5

readiness:
  enabled: true
  method: http
  service: web
  path: "/"
  initialDelaySeconds: 70
  periodSeconds: 1
  successThreshold: 1
  failureThreshold: 5

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

nodeSelector: { }

tolerations: [ ]

affinity: { }

command: |
  while true; do date; sleep 2; done
shell: "/bin/bash"

volumes:
 - name: aaa
   path: /aa
   size: 10Gi
   type: dynamic-pvc
   readOnly: false
   spec:
     storageClass: default
 - name: bbb
   path: /bbb
   type: static-pvc
   spec:
     claimName: my-static-claim

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

container:
  annotations: { }
  env:
    - name: HELLO
      value: "hello"
  securityContext: { }

initContainers:
  - name: test
    image: test:test
    command: |
      echo test
    shell: "/bin/bash"
    env:
      - name: TEST
        value: "test"
